config/routes.rb
CelCenter::Application.routes.draw do
  root :to => "home#index", :via => [:get, :post]
  #devise_for :users, :controllers => {:registrations => "registrations"}
  #resources :users

  #new code begin
  devise_for :users, :skip => [:registrations]
  devise_scope :user do
    get "signup",   :to => "accounts#new"
    get "signin",   :to => "devise/sessions#new"
    get "signout",  :to => "devise/sessions#destroy"
    get "cancel_user_registration", :to => "devise/registrations#cancel"
    post "user_registration",       :to => "users#create"
    get "new_user_registration",    :to => "accounts#new"
    get "edit_user_registration",   :to => "users#edit"
  end
  resources :users
  resources :accounts
  # new code end

  namespace :admin do
    resources :clients, controller: 'clients'
  end

  post '/admin/set_current_client', to: 'home#set_current_client'

  match '/emails' => 'mailings#index', :via => [:get, :post]

  match '/emails/comparison' => 'mailings#comparison', :via => [:get, :post]

  get '/email/:mailing_id/', to: redirect('/email/%{mailing_id}/detail')
  get '/email/:mailing_id/detail', to: 'mailings#detail'
  get '/email/:mailing_id/interval', to: 'mailings#interval'
  get '/email/:mailing_id/email_domains', to: 'mailings#email_domains'
  get '/email/:mailing_id/user_sources', to: 'mailings#user_sources'
  get '/email/:mailing_id/links', to: 'mailings#links'

  post '/email/time_series', to: 'mailings#time_series'

  match '/pages' => 'pages#index', :via => [:get, :post]
  get '/page/:page_id/detail',         to: 'pages#detail'
  get '/page/:page_id/action_sources', to: 'pages#action_sources'
  get '/page/:page_id/user_sources',   to: 'pages#user_sources'

  post '/page/time_series', to: 'pages#time_series'

  match '/typeahead' => 'typeahead#index', :via => [:get, :post]

  get '/pv/1.gif' => 'page_views#record_page_view'
end

app/models/client.rb
class Client < ActiveRecord::Base
  belongs_to :master_user, :class_name => :User, :foreign_key => :master_user_id, :autosave => true
  has_many :users, :inverse_of => :client

  accepts_nested_attributes_for :master_user

  validates_uniqueness_of :ak_schema_name    #, unless: :super_admin?
  validates_uniqueness_of :cc_schema_name    #, unless: :super_admin?

  def super_admin?
    self.id == 1
  end

  def ak_schema
    ak_schema_name
  end

  def cc_schema
    cc_schema_name
  end

  def tz_identifier 
    ActiveSupport::TimeZone.zones_map[time_zone].tzinfo.identifier
  end
  alias_method :tz, :tz_identifier

  def tz_offset
    ActiveSupport::TimeZone.zones_map[time_zone].formatted_offset
  end

  def Client.lookup_by_ak_domain(domain)
    c = self.cache_read(domain)

    if c.nil?
      c = Client.select(:id, :cc_schema_name).where(ak_domain: domain, active: true).first
      if c
        c
        self.cache_write(domain, c)
      else
        c = nil
      end
    end

    return c
  end

  private

  def self.cache_read(key)
    Rails.cache.read("#{self.to_s}:#{key}")
  end

  def self.cache_write(key, data)
    Rails.cache.write("#{self.to_s}:#{key}", data)
  end



end

app/controllers/admin/clients_controller.rb
class Admin::ClientsController < ApplicationController

  before_filter :authenticate_user!
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.where('active = true')
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
    @client.master_user = User.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    init_passwd = Devise.friendly_token

    ma = master_user_params()
    ma[:password] = init_passwd
    ma[:password_confirmation] = init_passwd
    ma[:time_zone] = client_only_params[:time_zone]

    @client = Client.new(client_only_params)

    Client.transaction do
      respond_to do |format|
        if @client.save
          @client.master_user = User.new(ma)
          @client.master_user.client = @client
          @client.master_user.save!
          @client.save!
          @client.master_user.add_role :admin
          @client.master_user.active = true; #Cat: Sanity check

          format.html { redirect_to admin_client_path(@client), notice: 'Client was successfully created.' }
          format.json { render action: 'show', status: :created, location: @client }
        else
          format.html { render action: 'new' }
          format.json { render json: @client.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to admin_client_path(@client), notice: 'Client was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.active = false
    @client.save!
    respond_to do |format|
      format.html { redirect_to admin_clients_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.includes(:master_user).find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params.require(:client).permit(:active, :admin, :name, :domain, :ak_domain, :ak_schema_name, :cc_schema_name, :time_zone, :page_significance_threshold, :email_action_threshold, :email_action_threshold_time, :default_timeframe, :master_user_attributes => [:id, :name, :email])
    end

    def client_only_params
      params.require(:client).permit(:active, :admin, :name, :domain, :ak_domain, :ak_schema_name, :cc_schema_name, :time_zone, :page_significance_threshold, :email_action_threshold, :email_action_threshold_time, :default_timeframe)
    end

    def master_user_params
      params.require(:client).permit(:master_user_attributes => [:name, :email])[:master_user_attributes]
    end

end

app/helpers/admin/clients_helper.rb
module Admin::ClientsHelper
end

app/views/admin/clients/_form.html.haml
= simple_form_for [:admin, @client] do |f|
  = f.error_notification
  = display_base_errors @client

  .form-inputs

    = f.input :name
    %div.clearfix10
    = f.input :time_zone do
      = f.time_zone_select('time_zone', ActiveSupport::TimeZone.us_zones)
    %div.clearfix10
    = f.input :ak_schema_name
    %div.clearfix10
    = f.input :cc_schema_name
    %div.clearfix10
    = f.input :domain
    %div.clearfix10
    = f.input :ak_domain
    %div.clearfix10

    = f.fields_for :master_user do |uf|
      = uf.input :name
      %div.clearfix10

      = uf.input :email,:input_html => { :class => 'expanded' }
    %div.clearfix10

    = f.input :active
    %div.clearfix10
    = f.input :page_significance_threshold
    %div.clearfix10
    = f.input :email_action_threshold
    =#%div.clearfix10
    =# f.input :email_action_threshold_time
    =#%div.clearfix10
    =# f.input :default_timeframe
    =#%div.clearfix10
  .form-actions
    = f.button :submit, :class => 'btn-primary'

=# <div class="control-group boolean optional client_active"><label class="boolean optional control-label" for="client_active">

app/views/admin/clients/edit.html.haml
%h3
  Edit client:
  = @client.name

= link_to "home", root_path
\|
= link_to 'clients', admin_clients_path
\|
= link_to @client.name.downcase, admin_client_path(@client)

%p
  %br

= render 'form'

app/views/admin/clients/index.html.haml
%div.h3-hdr
  Client organizations

-# TODO: add restriction here, do not show if not cel employee

%div.create-style
  = link_to '+{new client}', new_admin_client_path

%p
  %br

.span8
  %table.table.table-condensed

    %tr
      %th Active
      %th Admin
      %th Name
      %th AK Schema name
      %th CC Schema name
      %th Domain
      %th AK Domain
      %th User
      %th Email
      %th
      %th
      %th

    - @clients.each do |client|
      %tr
        %td= client.active
        %td= client.admin
        %td= client.name
        %td= client.ak_schema_name
        %td= client.cc_schema_name
        %td= client.domain
        %td= client.ak_domain
        %td= client.master_user.name
        %td= client.master_user.email
        %td= link_to 'Show', admin_client_path(client)
        %td= link_to 'Edit', edit_admin_client_path(client)
        %td= link_to 'Deactive', admin_client_path(client), :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

app/views/admin/clients/new.html.haml
%h3 New client

= link_to "home", root_path
\|
= link_to 'clients', admin_clients_path

%p
  %br

= render 'form'

app/views/admin/clients/show.html.haml
%h3#notice= notice

%h3
  Show Details:
  = @client.name

= link_to "home", root_path
\|
= link_to 'clients', admin_clients_path

%div{:style => 'padding: 0px 25px 0px 110px'}
  %p
    %b Active:
    = @client.active
  %p
    %b Timezone:
    = @client.time_zone
  %p
    %b Admin:
    = @client.admin
  %p
    %b Name:
    = @client.name
  %p
    %b AK Schema name:
    = @client.ak_schema_name
  %p
    %b CC Schema name:
    = @client.cc_schema_name
  %p
    %b Administrator:
    = @client.master_user.name
  %p
    %b Admin email:
    = @client.master_user.email

  %p
    %b Page significance threshold:
    = @client.page_significance_threshold

  %p
    %b Email action threshold (what % of actions to reach within the specified timeframe):
    = @client.email_action_threshold

  %p
    %b Display timeframe (for pages and mailings):
    = @client.default_timeframe

  = link_to '{Edit}', edit_admin_client_path(@client)