config/routes.rb
CelCenter::Application.routes.draw do
  root :to => "home#index", :via => [:get, :post]
  #devise_for :users, :controllers => {:registrations => "registrations"}
  #resources :users

  #new code begin
  devise_for :users, :skip => [:registrations]
  devise_scope :user do
    get "signup",   :to => "accounts#new"
    get "signin",   :to => "devise/sessions#new"
    get "signout",  :to => "devise/sessions#destroy"
    get "cancel_user_registration", :to => "devise/registrations#cancel"
    post "user_registration",       :to => "users#create"
    get "new_user_registration",    :to => "accounts#new"
    get "edit_user_registration",   :to => "users#edit"
  end
  resources :users
  resources :accounts
  # new code end

  namespace :admin do
    resources :clients, controller: 'clients'
  end

  post '/admin/set_current_client', to: 'home#set_current_client'

  match '/emails' => 'mailings#index', :via => [:get, :post]

  match '/emails/comparison' => 'mailings#comparison', :via => [:get, :post]

  get '/email/:mailing_id/', to: redirect('/email/%{mailing_id}/detail')
  get '/email/:mailing_id/detail', to: 'mailings#detail'
  get '/email/:mailing_id/interval', to: 'mailings#interval'
  get '/email/:mailing_id/email_domains', to: 'mailings#email_domains'
  get '/email/:mailing_id/user_sources', to: 'mailings#user_sources'
  get '/email/:mailing_id/links', to: 'mailings#links'

  post '/email/time_series', to: 'mailings#time_series'

  match '/pages' => 'pages#index', :via => [:get, :post]
  get '/page/:page_id/detail',         to: 'pages#detail'
  get '/page/:page_id/action_sources', to: 'pages#action_sources'
  get '/page/:page_id/user_sources',   to: 'pages#user_sources'

  post '/page/time_series', to: 'pages#time_series'

  match '/typeahead' => 'typeahead#index', :via => [:get, :post]

  get '/pv/1.gif' => 'page_views#record_page_view'
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  belongs_to :client

  validates_presence_of :email
  validates_uniqueness_of :email, :scope => :client_id

  def super_admin?
    return client.super_admin?
  end



  def admin?
    has_role?(:admin)
  end

  def tz_identifier
    ActiveSupport::TimeZone.zones_map[time_zone].tzinfo.identifier
  end
  alias_method :tz, :tz_identifier

  def tz_offset
    ActiveSupport::TimeZone.zones_map[time_zone].formatted_offset
  end

  def soft_delete
    # assuming you have deleted_at column added already
    update_attribute(:active, false)
  end

  def is_active?
    return self.active
  end

  def active_for_authentication?
    super && self.is_active?
  end

  def inactive_message
    "Sorry, this account has been deactivated."
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource :except => [:create]

  def index
    authorize! :index, @user, :message => 'Not authorized as an administrator.'
    @users = User.where(client_id: current_client.id)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.client = current_client
    @user.add_role :user if @user.roles.blank?
    @user.active = true

    if @user.save
      flash[:notice] = "Successfully created User."
      redirect_to users_path
    else
      render :action => 'new'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end
  
  def update
    authorize! :update, @user, :message => 'Not authorized as an administrator.'
    @user = User.find(params[:id])
    puts user_params
    if @user.update_attributes(user_params)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end
    
  def destroy
    authorize! :destroy, @user, :message => 'Not authorized as an administrator.'
    user = User.find(params[:id])
    unless user == current_user
      user.active = false
      user.save!
      redirect_to users_path, :notice => "User deactivate."
    else
      redirect_to users_path, :notice => "Can't delete yourself."
    end
  end

  def user_params
    if params[:user][:password].blank? && params[:user][:password_confirmation].blank?
      params[:user].delete(:password)
      params[:user].delete(:password_confirmation)
    end
    params.require(:user).permit(:id, :name, :email, :password, :password_confirmation, :role_ids, :active)
  end
end

app/views/users/_form.html.haml
= simple_form_for @user do |f|
  = f.error_notification
  = display_base_errors @user

  .form-inputs
    = f.input :name
    %div.clearfix10
    = f.input :email,:input_html => { :class => 'expanded' }
    %div.clearfix10
    = f.input :password
    %i{:style => "margin-left:120px;"}
      *leave blank if you do not want to update
    %div.clearfix10
    = f.input :password_confirmation
    %i
      *leave blank if you do not want to update
    %div.clearfix10
    - if current_user && current_user.admin?
      %div{:style => "margin-left: 140px;"}
        = f.input :role_ids, :collection => Role.all, :as => :radio_buttons, :label_method => lambda {|t| t.name.titleize}, :label => false, :item_wrapper_class => 'inline', checked: @user.role_ids.first
      %div.clearfix10
        = f.input :active
    %div.clearfix10

  .form-actions
    = f.button :submit, :class => 'padded'

app/views/users/_user.html.haml
.modal{:id => "role-options-#{user.id}", :style => "display: none;"}
  = simple_form_for user, :url => user_path(user), :html => {:method => :put, :class => 'form-horizontal' } do |f|
    .modal-body
      %a.close{"data-dismiss" => "modal"} ×{close}
      = f.input :role_ids, :collection => Role.all, :as => :radio_buttons, :label_method => lambda {|t| t.name.titleize}, :label => false, :item_wrapper_class => 'inline', checked: user.role_ids.first
      %div.clearfix1
      = f.submit "Change Role", :class => "btn"

app/views/users/edit.html.haml
%h3
  Edit User:
  = @user.name

= link_to "home", root_path

%p
  %br

= render 'form'

app/views/users/index.html.haml
%div.h3-hdr
  Users

- if current_user && current_user.admin?
  %div.create-style
    = link_to '+{new user}', new_user_path

=#Signed in as #{current_user.email}. Not you?
=# link_to "Sign out", destroy_user_session_path
%p
  %br
.span8
  %table.table.table-condensed
    %tr
      %th Username
      %th Email
      %th Registered
      %th Active
      %th Role
      %th
      %th


    %tbody
      - @users.each do |user|
        %tr
          %td= link_to user.name, user
          %td= user.email
          %td= user.created_at.to_date
          %td= user.active
          %td= user.roles.first.name.titleize unless user.roles.first.nil?
          %td
            = render user
            - if current_user.admin?
              /\|
              = link_to "Show", user_path(user)
              = "\|"
              = link_to "Edit", edit_user_path(user)
              = "\|" unless user == current_user || !user.is_active?
              = link_to("Deactivate", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete)  unless user == current_user || !user.is_active?

app/views/users/new.html.haml
%h3 Create New User

= link_to "home", root_path
\|
= link_to "users", users_path
\|
Organization:
= current_client.name

%p
  %br

= render 'form'

%p
  %br
  %i
    * New users will be sent a confirmation email to complete the registration process.

app/views/users/show.html.haml
%h3 User
%p
  User: #{@user.name}
%p
  Organization: #{current_client.name}
%p
  Email: #{@user.email if @user.email}
%p
  Role: #{@user.roles.first.name.titleize}
%p
  Active: #{@user.active}
%p
  Confirmed at: #{@user.confirmed_at}
%p
  Last Login: #{@user.last_sign_in_at}