config/routes.rb
CelCenter::Application.routes.draw do
  root :to => "home#index", :via => [:get, :post]
  #devise_for :users, :controllers => {:registrations => "registrations"}
  #resources :users

  #new code begin
  devise_for :users, :skip => [:registrations]
  devise_scope :user do
    get "signup",   :to => "accounts#new"
    get "signin",   :to => "devise/sessions#new"
    get "signout",  :to => "devise/sessions#destroy"
    get "cancel_user_registration", :to => "devise/registrations#cancel"
    post "user_registration",       :to => "users#create"
    get "new_user_registration",    :to => "accounts#new"
    get "edit_user_registration",   :to => "users#edit"
  end
  resources :users
  resources :accounts
  # new code end

  namespace :admin do
    resources :clients, controller: 'clients'
  end

  post '/admin/set_current_client', to: 'home#set_current_client'

  match '/emails' => 'mailings#index', :via => [:get, :post]

  match '/emails/comparison' => 'mailings#comparison', :via => [:get, :post]

  get '/email/:mailing_id/', to: redirect('/email/%{mailing_id}/detail')
  get '/email/:mailing_id/detail', to: 'mailings#detail'
  get '/email/:mailing_id/interval', to: 'mailings#interval'
  get '/email/:mailing_id/email_domains', to: 'mailings#email_domains'
  get '/email/:mailing_id/user_sources', to: 'mailings#user_sources'
  get '/email/:mailing_id/links', to: 'mailings#links'

  post '/email/time_series', to: 'mailings#time_series'

  match '/pages' => 'pages#index', :via => [:get, :post]
  get '/page/:page_id/detail',         to: 'pages#detail'
  get '/page/:page_id/action_sources', to: 'pages#action_sources'
  get '/page/:page_id/user_sources',   to: 'pages#user_sources'

  post '/page/time_series', to: 'pages#time_series'

  match '/typeahead' => 'typeahead#index', :via => [:get, :post]

  get '/pv/1.gif' => 'page_views#record_page_view'
end

app/models/ak_page.rb
class AkPage < ActiveRecord::Base
  self.table_name = "core_page"

  # Disables Active Record's STI which by default uses a column called 'type'
  # (core_page has a column called 'type'...)
  self.inheritance_column = '__noinheritance__'

  has_and_belongs_to_many :tags, :class_name => :AkTag, :join_table => 'core_page_tags',  :foreign_key => :page_id, :association_foreign_key => :tag_id
  has_many :fields, :class_name => AkPagefield, :foreign_key => :parent_id
  has_many :actions, :class_name => AkAction, :foreign_key => :page_id

  def as_json(*args)
    super.tap { |hash| hash["name"] = hash.delete "title"}
  end

  def AkPage.id_from_name(name)
    pid = self.cache_read(name)

    if pid.nil?
      p = AkPage.select(:id).where(name: name).first
      if p
        pid = p.id
        self.cache_write(name, pid)
      else
        pid = 0
      end
    end

    return pid
  end

  private

  def self.cache_read(key)
    Rails.cache.read("#{self.to_s}:#{key}")
  end

  def self.cache_write(key, data)
    Rails.cache.write("#{self.to_s}:#{key}", data)
  end

end

app/models/ak_tag.rb
class AkTag < ActiveRecord::Base
  self.table_name = "core_tag"

  has_and_belongs_to_many :mailings, :class_name => :AkMailing, :join_table => 'core_mailing_tags', :foreign_key => :tag_id, :association_foreign_key => :mailing_id
  has_and_belongs_to_many :pages,    :class_name => :AkPage,    :join_table => 'core_page_tags',    :foreign_key => :tag_id, :association_foreign_key => :page_id
end

app/views/pages/_list_table.html.haml
%table.table 
  %thead
    %tr
      %th
        ID
      %th
        Type
      %th
        Title
      %th
        Created
      %th
        Actions
      %th
        Members
      %th
        Delta
      %th
        Revenue
      - if !local_assigns[:show_graphit]
        %th
          Graph It!
  - if @rows.any?
    %tbody
      - @rows.each do |r|
        %tr{ :class => [cycle("odd", "even"), page_significance(r)], :data => {:page_id => r['page_id'] } }
          %td
            = link_to "#{r['page_id']}", "/page/#{r['page_id']}/detail"
            = link_to("https://#{current_client.ak_domain}/admin/core/page/#{r['page_id']}/", :target => '_blank') do
              %span.glyphicon.glyphicon-link{:title => "View page on Actionkit"}
          %td.page-type
            = r["type"]
          %td.title
            = link_to "#{r["title"]}", "/page/#{r['page_id']}/detail"
          %td
            = r["created_at"]
          %td
            = number_with_delimiter(r["actions"], :delimiter => ',')
          %td{:class => ('negative' if r["members"].to_i < 0) }
            = number_with_delimiter(r["members"], :delimiter => ',')
          %td{:class => ('negative' if r["members"].to_i < 0) }
            = pct(r["members"], r["list_size"])
          %td
            = number_to_currency(r["revenue"])
          - if !local_assigns[:show_graphit]
            %td
              %input.graph-ts.page-id{:type => "checkbox", :value => r["page_id"]}
  - else
    %tbody
      %tr
        %td{:colspan => '8'}
          Sorry, No rows returned!

app/views/pages/_page_details.html.haml
.row
  %div.chart-header-custom
    %div.summary
      %p
        %strong
          Title: 
        = @page.title
      %p
        %strong
          Type:
        #{@page.type}
        %strong
          Created:
        #{@page.created_at.to_date}
        - if @page.tags.size > 0
          %strong
            Tags: 
          #{@page.tags.collect{|t| t.name}.join(', ') }

  %div.col-md-8

app/views/pages/_tabs.html.haml
.container-fluid
  .row-fluid
    %ul.nav.nav-tabs
      %li{:class => "context_info", :style => "width: 359px"}
        - if local_assigns[:show_context_label]
          = "Page Id: #{show_context_label}"
      %li{:class => is_active?("detail")}
        = link_to "Detail", { controller: 'pages', action: 'detail' }
      %li{:class => is_active?("action_sources")}
        = link_to "Action Sources", { controller: 'pages', action: 'action_sources' }
      %li{:class => is_active?("user_sources")}
        = link_to "User Sources", { controller: 'pages', action: 'user_sources' }

:javascript
  var pageId = "#{params[:page_id]}";

app/views/pages/action_sources.html.haml
= render partial: "tabs",  locals: {show_context_label: @page.id}
= render partial: "page_details", locals: {show_chart: true}

- #global calculations begin
- total_actions = total_members = total_subscribers = total_revenue = 0
- @rows.each do |r|
  - total_actions += r["actions"].to_i
  - total_members += r["new_members"].to_i
  - total_subscribers += r['new_subscribers'].to_i
  - if @page.type == 'Donation'
    - total_revenue += r['revenue'].to_f
- #global calculations end

%div.row
  %div#PageDetailEventChart

%table.table
  %thead
    %tr
      %th
        ID
      %th
        Source
      %th
        Actions
      %th
        New Members
      %th
        Re-Subscribers
      - if @page.type == 'Donation'
        %th
          Revenue

  %tbody
    %tr{:style => "background: #F39C12;"}
      %td
      %td <b>Total</b>
      %td
        %b
          = number_with_delimiter(total_actions, :delimiter => ',')
      %td
        %b
          = number_with_delimiter(total_members, :delimiter => ',')
      %td
        %b
          = number_with_delimiter(total_subscribers, :delimiter => ',')
      - if @page.type == 'Donation'
        %td
          %b
            = number_to_currency(total_revenue)

    - counter = 0
    - @rows.each do |r|
      - zebra = (counter % 2 == 0 ? ' even' : ' odd')
      - counter += 1
      %tr{:class => "#{zebra}"}
        %td
          = r['source_id']
        %td.left
          = r['source']
        %td
          = r['actions']
          = "(#{pct(r["actions"], total_actions)})"
        %td{:class => ('negative' if r["members"].to_i < 0) }
          = r['new_members']
          = "(#{pct(r["new_members"], total_members)})"
        %td
          = r['new_subscribers']
          = "(#{pct(r["new_subscribers"], total_subscribers)})"
        - if @page.type == 'Donation'
          %td
            = number_to_currency(r['revenue'])

-# associated actionfields
- @supersize = false
.row
- @fields.each do |key, value|
  - if value > 10000
    - @supersize = true
  - else
    - @supersize = false

  - if (!key.include? "sharetrack") && !(key == "id")
    %div{:class => @supersize ? 'col-lg-4 text.center' : 'col-lg-3 text-center'}
      .panel.panel-success
        .panel-heading
          .row
            .col-xs-6
              - if key == "comment"
                %i.fa.fa-comments.fa-5x
              - elsif key.include? "sign"
                %i.fa.fa-list.fa-5x
              - else
                %i.fa.fa-check-square-o.fa-5x
            .col-xs-6.text-right
              %p.announcement-heading
                = number_with_delimiter(value, :delimiter => ',')
              %p.announcement-text
                - if key == "comment"
                  = key + "s"
                - else
                  = key

= javascript_include_tag 'dimple'
= javascript_include_tag 'pages'

:javascript
  window.Page = 'pageActionSource';
  Data = {};
  Data.pageSource = #{@chartData};
  var akPageType = '#{@page.type}'

app/views/pages/detail.html.haml
- #global calculations begin
- total_actions = total_members = total_subscribers = total_revenue = 0
- @rows.each do |r|
  - total_actions += r["actions"].to_i
  - total_members += r["members"].to_i
  - total_subscribers += r['new_subscribers'].to_i
  - if @page.type == 'Donation'
    - total_revenue += r['revenue'].to_f
- #global calculations end

= render partial: "tabs",  locals: {show_context_label: @page.id}
= render partial: "page_details", locals: {show_chart: true}

.clearfix10

-# progress bar
-# TODO: change to green if goal reached
- if @page.goal.present? && @page.goal != 0 && total_actions > 0
  .col-md-12
    .col-lg-12
      .progress.progress-striped{:style => "margin-bottom: 3px;"}
        - if total_actions >= @page.goal
          .progress-bar.progress-bar-success{:style =>  "width: #{(total_actions.to_f/@page.goal.to_f)*100}%"}
        - else
          .progress-bar.progress-bar-danger{:style =>  "width: #{(total_actions.to_f/@page.goal.to_f)*100}%"}
      %em
        #{number_with_delimiter(total_actions,:delimiter => ',')} actions taken out of goal: #{number_with_delimiter(@page.goal,:delimiter => ',')}

.clearfix10





%div.row
  %div#PageDetailEventChart

%div.panel.panel-default
  %div.panel-heading
    = form_tag("/page/#{@page.id}/detail", :method => :get, :class => "navbar-form", :id => "tableFilter") do
      %div#dateFilterStart.form-group
        = label_tag(:activity_start_dt, "Activity Date", :class => "")
        = date_field_tag(:activity_start_dt, "#{@filter_params[:activity_start_dt]}", class: "start_dt")
      %div#dateFilterEnd.form-group
        = label_tag(:activity_end_dt, "", :class => "")
        To 
        =date_field_tag(:activity_end_dt, "#{@filter_params[:activity_end_dt]}", class: "end_dt")

      = submit_tag("Search", class: "btn btn-primary")
      = button_tag("Reset", class: "btn btn-warning", id: "reset")


%table.table
  %thead
    %tr
      %th
        Date
      %th
        Actions
      %th
        New Members
      %th
        Re-Subscribers
      - if @page.type == 'Donation'
        %th
          Revenue
      %th

  %tbody
    %tr{:style => "background: #F39C12;"}
      %td <b>Total</b>
      %td
        %b
          = number_with_delimiter(total_actions, :delimiter => ',')
      %td
        %b
          = number_with_delimiter(total_members, :delimiter => ',')
      %td
        %b
          = number_with_delimiter(total_subscribers, :delimiter => ',')
      - if @page.type == 'Donation'
        %td
          %b
            = number_to_currency(total_revenue)
      %td

    - counter = 0
    - @rows.each do |r|
      - zebra = (counter % 2 == 0 ? ' even' : ' odd')
      - counter += 1

      %tr{:class => "#{zebra}"}
        %td
          = r['period'].to_time.strftime("%b %e, %Y: %l:%M %p")
        %td
          = number_with_delimiter(r['actions'], :delimiter => ',')
          = "(#{pct(r["actions"], total_actions)})"
        %td{:class => ('negative' if r["members"].to_i < 0) }
          = number_with_delimiter(r['members'], :delimiter => ',')
          = "(#{pct(r["members"], total_members)})"
        %td
          = number_with_delimiter(r['new_subscribers'], :delimiter => ',')
          = "(#{pct(r["new_subscribers"], total_subscribers)})"
        - if @page.type == 'Donation'
          %td
            = number_to_currency(r['revenue'])
        %td

= javascript_include_tag 'dimple'
= javascript_include_tag 'pages'

:javascript
  var akPageType = '#{@page.type}'
  window.Page = 'pageDetail';
  Data = {};
  Data.pageDetail = #{@chartData};

app/views/pages/index.html.haml
- end_date   = @filter_params[:activity_end_dt].nil?   ? DateTime.now  : DateTime.parse(@filter_params[:activity_end_dt])
- start_date = @filter_params[:activity_start_dt].nil? ? end_date - 14 : DateTime.parse(@filter_params[:activity_start_dt])

%h4{:style => "padding-left:15px;"}
  - divider = false
  Page(s)
  / page id
  - if !@filter_params[:page_ids].blank?
    Ids:
    = @filter_params[:page_ids]
    - divider = true

  / mailing id
  - if !@filter_params[:mailing_ids].blank?
    - if !divider
      - divider = true
    - else
      %span{:style => 'color: #517d94;'}
        |
    Mailing(s):
    = @filter_params[:mailing_ids]

  / tags
  - if !@filter_params[:tag_ids].blank?
    - if !divider
      - divider = true
    - else
      %span{:style => 'color: #517d94;'}
        |
    Tag(s):
    = @filter_params[:tag_ids]

  / divider for date
  - if divider
    %span{:style => 'color: #517d94;'}
      |

  Activity:
  = start_date.strftime("%b %e, %Y")
  to
  = end_date.strftime("%b %e, %Y")


- if @rows.any?
  %span#only-significant-pages
    %input{:type => :checkbox, :checked => true}
    Show Signifcant Pages Only

- if @rows.any?
  %div.chart.pages
    %div.chart-header
      %h2.chart-title.pull-left
      %div.chart-controls
    %div#SummaryEventChart
    %div#SummaryTimeSeriesChart

%div.panel.panel-default
  %div.panel-heading
    = form_tag("/pages", :method => :post, :class => "navbar-form", :id => "tableFilter") do
      %div#pageIdFilter.form-group
        = label_tag(:page_ids, "Page(s)", :class => "")
        = search_field_tag(:page_ids, "#{@filter_params[:page_ids]}", { :placeholder => "Enter Page ID(s)"})
      %div#dateFilterStart.form-group
        = label_tag(:activity_start_dt, "Activity Date", :class => "")
        = date_field_tag(:activity_start_dt, "#{@filter_params[:activity_start_dt]}", class: "start_dt")
      %div#dateFilterEnd.form-group
        = label_tag(:activity_end_dt, "", :class => "")
        To 
        =date_field_tag(:activity_end_dt, "#{@filter_params[:activity_end_dt]}", class: "end_dt")
      %div#pageIdFilter.form-group
        = label_tag(:page_ids, "Mailing Id(s)", :class => "")
        = search_field_tag(:mailing_ids, "#{@filter_params[:mailing_ids]}", {:placeholder => "Enter Mailing ID(s)"})
      %div#tagFilter.form-group
        = label_tag(:tag_ids, "Tag(s)", :class => "")
        = search_field_tag("tag_ids", "#{@filter_params[:tag_ids]}", { :placeholder => "Enter Tag ID(s)"})

      = submit_tag("Search", class: "btn btn-primary")
      = button_tag("Reset", class: "btn btn-warning", id: "reset")
      
  %table.table    
    = render partial: "list_table", locals: { show_subject: nil, overview: true }

= javascript_include_tag "dimple"
= javascript_include_tag "pages"

:javascript
  window.Page = 'pageList';
  window.Data = {};

  Data.filterParams = { 
    'tag': #{(@filter_params[:tag_ids] ? "\"#{@filter_params[:tag_ids]}\"" : 'null')},
    'page': #{(@filter_params[:page_ids] ? "\"#{@filter_params[:page_ids]}\"" : 'null')},
    // 'mailing': #{(@filter_params[:mailing_ids] ? "\"#{@filter_params[:mailing_ids]}\"" : 'null')}
    // 'domain': #{(@filter_params[:domain_ids] ? "\"#{@filter_params[:domain_ids]}\"" : 'null')},
    // 'user_source': #{(@filter_params[:user_source_ids] ? "\"#{@filter_params[:user_source_ids]}\"" : 'null')}
  }
  Data.pageListSummary = #{@summaryChartData};
  Data.pageSignificanceThreshold = #{ current_client.page_significance_threshold };

app/views/pages/user_sources.html.haml
= render partial: "tabs",  locals: {show_context_label: @page.id}
= render partial: "page_details", locals: {show_chart: true}


- #global calculations begin
- total_actions = total_members = total_subscribers = total_revenue = 0
- @rows.each do |r|
  - total_actions += r["actions"].to_i
  - total_members += r["new_members"].to_i
  - total_subscribers += r['new_subscribers'].to_i
  - if @page.type == 'Donation'
    - total_revenue += r['revenue'].to_f
- #global calculations end

%div.row
  %div#PageDetailEventChart

%table.table
  %thead
    %tr
      %th
        ID
      %th
        Source
      %th
        Actions
      %th
        New Members
      %th
        Re-Subscribers
      - if @page.type == 'Donation'
        %th
          Revenue

  %tbody
    %tr{:style => "background: #F39C12;"}
      %td
      %td <b>Total</b>
      %td
        %b
          = number_with_delimiter(total_actions, :delimiter => ',')
      %td
        %b
          = number_with_delimiter(total_members, :delimiter => ',')
      %td
        %b
          = number_with_delimiter(total_subscribers, :delimiter => ',')
      - if @page.type == 'Donation'
        %td
          %b
            = number_to_currency(total_revenue)

    - counter = 0
    - @rows.each do |r|
      - zebra = (counter % 2 == 0 ? ' even' : ' odd')
      - counter += 1
      %tr{:class => "#{zebra}"}
        %td
          = r['source_id']
        %td.left
          = r['source']
        %td
          = number_with_delimiter(r['actions'], :delimiter => ',')
          = "(#{pct(r["actions"], total_actions)})"
        %td{:class => ('negative' if r["members"].to_i < 0) }
          = number_with_delimiter(r['new_members'], :delimiter => ',')
          = "(#{pct(r["new_members"], total_members)})"
        %td
          = number_with_delimiter(r['new_subscribers'], :delimiter => ',')
          = "(#{pct(r["new_subscribers"], total_subscribers)})"
        - if @page.type == 'Donation'
          %td
            = number_to_currency(r['revenue'])

-# associated actionfields
  .row
  - @fields.each do |key, value|
    - if key == "comment"
      .col-lg-3.text-center
        .panel.panel-info
          .panel-heading
            .row
              .col-xs-6
                %i.fa.fa-comments.fa-5x
              .col-xs-6.text-right
                %p.announcement-heading
                  = number_with_delimiter(value, :delimiter => ',')
                %p.announcement-text
                  = key + "s"
    - elsif (!key.include? "sharetrack") && !(key == "id")
      .col-lg-3.text-center
        .panel.panel-info
          .panel-heading
            Action Field:
            = key
            .panel-body.text-center
              Count:
              = value

= javascript_include_tag 'dimple'
= javascript_include_tag 'pages'

:javascript
  window.Page = 'pageActionSource';
  window.Data = {};
  Data.pageSource = #{@chartData};
  var akPageType = '#{@page.type}';