config/routes.rb
CelCenter::Application.routes.draw do
  root :to => "home#index", :via => [:get, :post]
  #devise_for :users, :controllers => {:registrations => "registrations"}
  #resources :users

  #new code begin
  devise_for :users, :skip => [:registrations]
  devise_scope :user do
    get "signup",   :to => "accounts#new"
    get "signin",   :to => "devise/sessions#new"
    get "signout",  :to => "devise/sessions#destroy"
    get "cancel_user_registration", :to => "devise/registrations#cancel"
    post "user_registration",       :to => "users#create"
    get "new_user_registration",    :to => "accounts#new"
    get "edit_user_registration",   :to => "users#edit"
  end
  resources :users
  resources :accounts
  # new code end

  namespace :admin do
    resources :clients, controller: 'clients'
  end

  post '/admin/set_current_client', to: 'home#set_current_client'

  match '/emails' => 'mailings#index', :via => [:get, :post]

  match '/emails/comparison' => 'mailings#comparison', :via => [:get, :post]

  get '/email/:mailing_id/', to: redirect('/email/%{mailing_id}/detail')
  get '/email/:mailing_id/detail', to: 'mailings#detail'
  get '/email/:mailing_id/interval', to: 'mailings#interval'
  get '/email/:mailing_id/email_domains', to: 'mailings#email_domains'
  get '/email/:mailing_id/user_sources', to: 'mailings#user_sources'
  get '/email/:mailing_id/links', to: 'mailings#links'

  post '/email/time_series', to: 'mailings#time_series'

  match '/pages' => 'pages#index', :via => [:get, :post]
  get '/page/:page_id/detail',         to: 'pages#detail'
  get '/page/:page_id/action_sources', to: 'pages#action_sources'
  get '/page/:page_id/user_sources',   to: 'pages#user_sources'

  post '/page/time_series', to: 'pages#time_series'

  match '/typeahead' => 'typeahead#index', :via => [:get, :post]

  get '/pv/1.gif' => 'page_views#record_page_view'
end

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name == :notice ? "success" : "danger"}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
%nav.navbar.navbar-default{role: "navigation"}
  %div.container-fluid

    - if user_signed_in?

      %div.navbar-header
        %button.navbar-toggle{type: "button", data: {toggle: "collapse", target: "#bs-example-navbar-collapse-1"} }
          %span.sr-only
            Toggle navigation
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        %a.navbar-brand
          = image_tag 'CEL-blue-transparent.png', {:width => 100, :height => 20}

      %div.collapse.navbar-collapse#bs-example-navbar-collapse-1
        %ul.nav.navbar-nav

          %li{:class => (current_page?('/') ? "active" : nil)}
            %a{:href => "/" }
              Overview

          %li{:class => (controller_name == 'mailings' ? "active" : nil)}
            %a{:href => "/emails"}
              Mailings

          %li{:class => (controller_name == 'pages' ? "active" : nil)}
            %a{:href => "/pages"}
              Pages

          %li.dropdown
            %a.dropdown-toggle{href: "#", data: {toggle: "dropdown"} }
              Settings
              %span.caret

            %ul.dropdown-menu{role: "menu"}
              %li
                = link_to 'Account', edit_user_path(current_user)
              - if current_user && current_user.admin?
                %li
                  = link_to 'Users', users_path
              - if current_user && current_user.super_admin?
                %li
                  = link_to 'Clients', admin_clients_path
              %li{:class => "last"}
                = link_to 'Logout', destroy_user_session_path, :method=>'delete'

        %ul.nav.navbar-nav.navbar-right
          - if current_client
            %li#lastSync
              %a
                = last_sync()

        - if current_user && current_user.super_admin? && Client.count > 1
          = form_tag('/admin/set_current_client', method: :post, id: 'select_client', class: 'navbar-form navbar-right', role: 'search') do
            %div.form-group
              %label{:style => "text-decoration: none; font-size: 13px; font-weight: 700; color: #fff; text-transform: uppercase; letter-spacing: 1px;"}
                CLIENT:
              %select#current_client{:name => 'client_id'}
                = options_from_collection_for_select(@available_clients, :id, :name, current_client.id)

    - else
      %div.collapse.navbar-collapse#bs-example-navbar-collapse-1
        %ul.nav.navbar-nav
          %li.active
            = link_to 'Login', new_user_session_path

app/views/layouts/_navigation_links.html.haml
- if user_signed_in?
  %li 
    = link_to 'Mailings', '/emails'
  %li
    = link_to 'Users', users_path
  %li
    = link_to current_user.name, edit_user_path(current_user)
  %li
    = link_to 'Logout', destroy_user_session_path, :method=>'delete'

- else
  %li
    = link_to 'Login', new_user_session_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Cel Center'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Cel Center'}"}
    = stylesheet_link_tag "application", media: "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    = render 'layouts/navigation'
    %main{:role => "main"}
      = render 'layouts/messages'
      = yield